name: CI - QA Test

on:
  workflow_dispatch:
  pull_request:

jobs:
  rune2e:
    name: Run e2e
    runs-on: ubuntu-latest

    steps:
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: Checkout qa test repo
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Setup node version
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm install
      - run: num run wdio
      - run: |
        cd features/apis
        mvn clean test -Dtest=IndividualRunner
        cd ../.. 
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        if: always()
        with:
          name: allure-results
          path: allure-results
          retention-days: 1
